name: Deploy Docker Compose (s10)

on:
  push:
    branches:
      - main  # change if you want another branch

jobs:
  deploy:
    name: Deploy Compose File
    runs-on: ubuntu-latest
    environment: s10

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose-plugin
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version
          docker compose version

      # 3. Log in to Docker registry using secrets
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4. Deploy with Docker Compose
      - name: Deploy Compose stack
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}   # e.g. devopseasylearning/s7edem-do-it-yourself-ui
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}     # e.g. latest
        run: |
          # Pull latest image
          docker pull $IMAGE_NAME:$IMAGE_TAG

          # Bring up services from docker-compose.yml
          docker compose up -d --build

