name: CI/CD Build a compose for voting app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov security scan
        run: |
          echo "🔍 Running Checkov scan..."
          checkov -d . --quiet --compact --soft-fail

      - name: Deploy with Docker Compose
        run: |
          echo "🚀 Starting Docker Compose deployment"
          docker compose up -d
