name: Deploy Compose (s10)

on:
  push:
    branches:
      - main   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: s10

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Docker & Compose
      - name: Install Docker and Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose-plugin
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version
          docker compose version

      # 3. Deploy using docker-compose.yml
      - name: Deploy Compose stack
        run: |
          docker compose pull
          docker compose up -d

