name: Deploy Compose (s10)

on:
  push:
    branches:
      - main   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: s10

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Docker and latest Compose
    
         # Install latest Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # 3. Deploy using docker-compose.yml
      - name: Deploy Compose stack
        run: |
          docker-compose pull
          docker-compose up -d


